apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-title
data:
  title: "Welcome to the course kubernetes and gitops!"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-depl
  labels:
    app: nginx-depl
spec:
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 2
  selector:
    matchLabels:
      app: nginx-depl
  template:
    metadata:
      labels:
        app: nginx-depl
    spec:
      volumes:
        - name: static
          emptyDir: {}
        - name: nginx-title
          configMap:
            name: nginx-title
      initContainers:
        - name: pre-startup-nginx
          image: docker/whalesay
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
            - -c
          args:
            - echo "<h1>$title</h1><pre>$(cowsay -b 'Hello Kubernetes from Mario')</pre>" > /static/index.html
          env:
            - name: title
              valueFrom:
                configMapKeyRef:
                  key: title
                  name: nginx-title
          volumeMounts:
            - mountPath: /static
              name: static
      containers:
        - name: nginx-main
          image: nginx:latest
          imagePullPolicy: IfNotPresent

          command:
            - /bin/sh
            - -c
          args:
            - echo "My name is $POD_NAME which have IP $POD_IP located in node $NODE_NAME in namespace $POD_NAMESPACE" >> /usr/share/nginx/html/index.html; nginx -g "daemon off;"
          volumeMounts:
            - mountPath: /usr/share/nginx/html
              name: static
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP

